# Generated by Django 3.1.7 on 2021-02-25 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_model', models.JSONField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
